spring:
  application:
    name: chatws
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: chatws123
    key-store-type: PKCS12
    key-alias: chatws
    enabled: true
